### ISSUE TITLE
Add JWT authn policy

### ISSUE THREAD

**Issue by sloria** [aio-libs/aiohttp-security#1]
I could work on a PR if there is interest in adding this.

**Comment by asvetlov** [comment]
Would be cool

**Comment by kamikaze** [comment]
no PR?

**Comment by asvetlov** [comment]
The issue is waiting for a hero.
For you maybe?

**Comment by sloria** [comment]
Sorry I never got around to this. I don't have time to work on this these days--hoping someone else can pick this up.

**Comment by d21d3q** [comment]
I would suggest (to a hero) to make it more generic about tokens with special case of JWT.

**Comment by asvetlov** [comment]
Fixed by #147
