### ISSUE TITLE
Upload the latest version to Pypi

### ISSUE THREAD

**Issue by franckinux** [aio-libs/aiohttp-security#103]
Hello,
can you upload the latest version to Pypi ?
The latest release on github is 0.1.1 (2016-10-22)
The latest release on Pypi is 0.1.0 (2016-01-18).
This simplifies our requirements.txt !
Thank you
F

**Comment by jettify** [comment]
I can do this tonight, may be someone can do this earlier.

**Comment by asvetlov** [comment]
@jettify please do

**Comment by jettify** [comment]
new version available on pypi https://pypi.python.org/pypi/aiohttp_security/0.1.1

**Comment by franckinux** [comment]
Thank you !
