### ISSUE TITLE
Is this production-ready?

### ISSUE THREAD

**Issue by koddr** [aio-libs/aiohttp-security#108]
Hello. Simple question about your package: is his production-ready?

I mean, I would like to start new project with aiohttp, but [aiohttp-security](https://github.com/aio-libs/aiohttp-security) is official aio-libs package and hasn't basic examples and google results to solve newbie questions (I'm newbie on aiohttp, using Django all time). And your package looks very good, have more useful examples than aiohttp-security 👍

**Comment by asvetlov** [comment]
It is ready in terms of API stability but has no examples and several useful utilities.
I have a plan for improvement the situation but unfortunately now I'm concentrated on aiohttp core mostly.

**Comment by koddr** [comment]
@asvetlov Thanks.
