### ISSUE TITLE
Decorators login_required with web.View

### ISSUE THREAD

**Issue by alk3mist** [aio-libs/aiohttp-security#132]
Hello. Is there a way to use login_required decorator with a class based view?

**Comment by asvetlov** [comment]
No. Please call `is_anonymous()` http://aiohttp-security.readthedocs.io/en/latest/reference.html#aiohttp_security.is_anonymous explicitly.

**Comment by alk3mist** [comment]
OK, thank you.

**Comment by d21d3q** [comment]
Is it on the road map?

**Comment by asvetlov** [comment]
Because decorator is applied to web handler: an async function which accepts the only request parameter and returns a response.
Have no idea where do you want to apply the deco: to class itself or to methods like `.get` but the signature is different anyway

**Comment by d21d3q** [comment]
Writing rest api, on one endpoint every logged in user can `get`, but user with special permission can `post/put/delete`.

**Comment by junxi3166** [comment]
You can try this.

`
def valid_login(func):  
    """This function applies only to class views."""
    @wraps(func)
    async def inner(cls, *args, **kwargs):
        session = await get_session(cls.request)
        uid = session.get("uid")
        if uid:
            user = await fetchone('select id, name, email, phone from user where id = %s', (uid,))
            cls.request.userdata = user
            return await func(cls, *args, **kwargs)
        else:
            return web.Response(status=302, headers={'location': '/login'})

    return inner
`

`
class QuestionChoices(web.View):
    """a web view"""

    @valid_login
    async def get(self):
        return web.Response(text='q-get')

    @valid_login
    async def post(self):
        return web.Response(text='q-post')
`

**Comment by NotSqrt** [comment]
Possible inspiration : the way django does it : https://docs.djangoproject.com/en/dev/topics/class-based-views/intro/#decorating-the-class
