### ISSUE TITLE
Installing requirements-dev.txt is failed.

### ISSUE THREAD

**Issue by alexpantyukhin** [aio-libs/aiohttp-security#144]
I was trying to run `pip install -r requirements-dev.txt` and there is the log:
```
Obtaining file:///D:/Work/github/aiohttp-security (from -r requirements-dev.txt
(line 1))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "D:\Work\github\aiohttp-security\setup.py", line 22, in <module>
        version = re.findall(r"^__version__ = '([^']+)'$", fp.read(), re.M)[0]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Work\github\aiohttp-security\setup.py", line 24, in <module>
        raise RuntimeError('Unable to determine version.')
    RuntimeError: Unable to determine version.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in D:\Work\github\ai
ohttp-security\
```

pip version: 9.0.3
python version: 3.5.0
os: windows 7

**Comment by asvetlov** [comment]
I recall problems with Windows CRLF v.s. Unix LF.
`setup.py` was tested on Unix only.
If you'll create a PR with Windows fix -- I'll review it.

**Comment by alexpantyukhin** [comment]
@asvetlov I have PR which fixes reading on windows machine. It seems to be working for me, but Im still have an issue during the installing on next steps :)

**Comment by asvetlov** [comment]
I'm wondering how deprecated *universal newlines* `U` mode can help (`open()` has `newline=None` parameter which works like `U` and enabled by default)

**Comment by alexpantyukhin** [comment]
Yes.. you are right! thanks! I removed `U` parameter.
