### ISSUE TITLE
Writing extended data into session

### ISSUE THREAD

**Issue by papaslen** [aio-libs/aiohttp-security#177]
Can you explain me something?

Method **SessionIdentityPolicy.remember()** has **kwargs as one of the parameters, but never use it to write data into user session dict. What's the point of this param?

For now in my project I have my own **SessionPolicy** implementation inherited from SessionIdentityPolicy, just in order to have a posibility of storing extended data in session (_like different datetimes, uuids, IPs etc._).

So, my question is: was Session Policy designed to be self implemented by users or am I wrong and there is special way to write extra data into session?

**Comment by asvetlov** [comment]
I think you can use aiohttp_security for checking user permissions and `await aiohttp_session.get_session()` for working with session storage at the same time.
No need to invent a new concept for mixing both session and security inside the same class.
They are different concepts.
