### ISSUE TITLE
Authorize decorator

### ISSUE THREAD

**Issue by shicky** [aio-libs/aiohttp-security#2]
I am currently using aiohttp_security for our new server.
I think it would be nice to include decorator in aiohttp_security api.
This is method signature I currently have.

``` python
@aiohttp_security.authorize(required=True, redirect_url=None, permission=None)
def handler(request):
    return web.Response(body=b'OK')
```

Can I create pull request?

**Comment by asvetlov** [comment]
Done by alternative way
