### ISSUE TITLE
Non-SA MySQL Example (Inside)

### ISSUE THREAD

**Issue by TensorTom** [aio-libs/aiohttp-security#283]
I don't feel like forking and doing a PR. I made this mysql code to replace the SA code (I hate SA). You should add it as an example:

Edit: Nevermind. Regular contributors say they don't want code suggestions in issues.

**Comment by asvetlov** [comment]
This project is created and supported by volunteers at spare time.

DB example is contributed by @dfee if I don't mistake.
If you want to contribute another usage example -- you are welcome.
If not -- that's fine also; but please don't require from us to do some work just for you if we not interesting in it. Open source software doesn't work in this way.

**Comment by thijstriemstra** [comment]
> I don't feel like forking and doing a PR. You should add it as an example

That's a weird point of view. You shouldn't demand things when working with an opensource project.

**Comment by TensorTom** [comment]
> > I don't feel like forking and doing a PR. You should add it as an example
> 
> That's a weird point of view. You shouldn't demand things when working with an opensource project.

Was just a suggestion. I presume to demand nothing.

**Comment by TensorTom** [comment]
Edited OP
