### ISSUE TITLE
online docs

### ISSUE THREAD

**Issue by alxpy** [aio-libs/aiohttp-security#29]
It would be cool to be able to read the documentation online. Do you planning to upload it to readthedocs?

P.S. Can I help you with that?

**Comment by jettify** [comment]
Sure you can help! Documentation contribution very appreciated in any aio-libs project, from small typo fixed to documentation entires!

**Comment by alxpy** [comment]
1) now we have https://aiohttp-security.readthedocs.io/
2) give me your readthedocs user and I add you to admin group
3) in this moment build of documentation does not work (I use my fork): look ~https://github.com/aio-libs/aiohttp-security/pull/25~ https://github.com/aio-libs/aiohttp-security/pull/20

**Comment by jettify** [comment]
Merged fix, could you rebuild docs from this repo?

**Comment by alxpy** [comment]
Done.
https://github.com/aio-libs/aiohttp-security/pull/30

**Comment by alxpy** [comment]
https://github.com/aio-libs/aiohttp-security/pull/32

**Comment by jettify** [comment]
thanks! i will provide user names tonight

**Comment by jettify** [comment]
i saw you added users, thanks!
