### ISSUE TITLE
Fix cookie related failures on master for python3.4

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiohttp-security#31]

**Comment by jettify** [comment]
@alxpy would you like also to figure out this issue? See failed example https://travis-ci.org/aio-libs/aiohttp-security/jobs/194297513

**Comment by alxpy** [comment]
I wanted try fix it. I'll see this evening or tomorrow.

**Comment by jettify** [comment]
@asvetlov pointed to this issue https://github.com/KeepSafe/aiohttp/issues/1485

**Comment by jettify** [comment]
@thehesiod since you are author of  https://github.com/KeepSafe/aiohttp/pull/1453 , could you please take a look on this failure, you may have valuable suggestions.

**Comment by thehesiod** [comment]
see cmt: https://github.com/KeepSafe/aiohttp/issues/1485

**Comment by jettify** [comment]
@alxpy looks like we found issue, turns out to be bug in python 4.3.2, checkout https://github.com/KeepSafe/aiohttp/issues/1485

**Comment by alxpy** [comment]
+1
