### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by bitnom** [aio-libs/aiohttp-security#517]
I would like to offer some help going through these PRs and issues. This package is really important to me.

**Comment by Dreamsorcerer** [comment]
I'll check if the CI can be sorted with one of the open PRs, and see what else needs sorting.

The last thing I was looking at was #371, but wanted feedback from @asvetlov as to what the intended design was, as the documentation says the `identity` should be `str`, but one of the examples uses `int`. If we make it flexible to allow any type though, then we lose type safety, I can't see any way to make the API generic without resorting to `Any`.

**Comment by Dreamsorcerer** [comment]
OK, up and running again.
First thing we need to do is remove the ignore at:
https://github.com/aio-libs/aiohttp-security/blob/master/setup.cfg#L8
And add 3.11 to:
https://github.com/aio-libs/aiohttp-security/blob/master/.github/workflows/ci.yaml#L52

And fix all the errors that appear.
